services:
  website:
    container_name: website
    image: nginx
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.website.rule=Host(`zibby.technology`,`website.zibby.technology`, `www.zibby.technology`)
      - traefik.http.routers.website.entrypoints=web-secure
      - traefik.http.routers.website.tls.certresolver=le
      - traefik.http.routers.website.middlewares=secured@file
      - traefik.http.middlewares.website.redirectscheme.scheme=https
      - traefik.frontend.headers.STSSeconds=31536000
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
    volumes:
      - ./content:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
      - ./cache:/var/cache/nginx
      - ./logs:/var/log/nginx
    networks:
      - traefik_default
networks:
  traefik_default:
    external: true
