services:
  website:
    container_name: website-test
    image: nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./content:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
      - ./logs:/var/log/nginx
